### ISSUE TITLE
[GENERAL] Crash during attempt to trace more than 4096 characters

### ISSUE THREAD

**Issue by svlad-90** [dterletskiy/carpc#15]
It seems that the framework is causing a crash once the length of the trace string exceeds the limit.

Try out to use MSG_INF with a string of more than 4096 lengths.

Part of obtained call stack:

37198 2022/04/19 18:01:19.965921 115210.4142 177 ECU1 DLCF MAIN 887876 log info verbose 1 04-19 20:47:58.621 12153 12153 F DEBUG   :       #00 pc 0000000000002270  /vendor/lib64/tda.carpc.tracing.shared.so (carpc::trace::to_android(carpc::trace::eLogLevel const&)+0) (BuildId: 6faa9b69801d65b58d1c63e79b7b58fd)
37202 2022/04/19 18:01:19.965948 115210.4149 179 ECU1 DLCF MAIN 887876 log info verbose 1 04-19 20:47:58.621 12153 12153 F DEBUG   :       #01 pc 000000000002f11e  /vendor/bin/epam/epam_android.hardware.automotive.vehicle@2.0-service (void carpc::trace::Logger::message<char const*, char const*, int, char const*, char const*>(carpc::trace::eLogLevel const&, char const*, char const*, char const*, int, char const*, char const*)+174) (BuildId: c6984a2f805895c54b16635dc5db3d4a)
37203 2022/04/19 18:01:19.965957 115210.4186 180 ECU1 DLCF MAIN 887876 log info verbose 1 04-19 20:47:58.621 12153 12153 F DEBUG   :       #02 pc 000000000002ebf4  /vendor/bin/epam/epam_android.hardware.automotive.vehicle@2.0-service (void carpc::trace::Logger::message_format<char const*, unsigned long>(carpc::trace::eLogLevel const&, char const*, char const*, int, char const*, char const*, unsigned long)+196) (BuildId: c6984a2f805895c54b16635dc5db3d4a)

**Comment by dterletskiy** [comment]
Reported from version 3.7.2 but really presents much earlier.

**Comment by dterletskiy** [comment]
Fixed in version 3.8.12
